### PR TITLE
Updated method to read the Web and Core xml file for Swagger Request and Response

### PR DESCRIPTION
**Pull request by anuj2020**
Updated the GetXmlFilesPaths in SwaggerConfig.cs file to read the both (Web & Core) xml file for swagger comments.

### Problem
Currently system is reading only .Web.xml file. And the API request/response properties class is available in .Core.xml. So the properties help description comments is not showing in Swagger

### Solution
A xml read file method has been updated by reading both (Web.xml, Core.xml) files.

### Proposed of changes
To show the API properties explanation in Swagger which will help developer/user to know about the properties.

### Additional context (optional)
It will be good if you can also do the one small testing of code at your end.

### Make sure these boxes are checked:
- [ ] Check all the changes in github PR - files count (non of them are redundant, have meaningful changes, all are added), if target branch is correct
- [ ] Check methods and variable namings - it should be self descriptive, no typos
- [ ] Check you did not introduce breaking changes in API and public models/services.
- [ ] Respect extensibility - https://community.virtocommerce.com/t/extensibility-basics-the-domain-model-and-persistence-layer-extension/141
- [ ] Follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and [SOLID](https://en.wikipedia.org/wiki/SOLID) principles
- [ ] For unit tests - follow Microsoft best practices: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
- [ ] Consolidate solution dependencies in case you are using newer version, update VC module dependencies in module.manifest. Do not upgrade 3rd party packages that are shipped with the platform with the version newer than in the platform.
- [ ] Check code style conventions - https://github.com/VirtoCommerce/styleguide/blob/master/csharp.md
- [ ] Check PR have a concise and descriptive title, follow [git commit message rules](https://github.com/VirtoCommerce/styleguide/blob/master/gitcommits.md)

### CODE REVIEW

**Comment by mvktsk** [comment]
Review task https://virtocommerce.atlassian.net/browse/VP-4537 has been created

**Review by tatarincev — COMMENTED** [review]
Seems you have made PR using an incorrect target and source branch.  For all PRs to the platform version 2.x need to use as source and target branch  https://github.com/VirtoCommerce/vc-platform/tree/support/2.x-dev.
Could you recreate your PR from this branch?

**Comment by anuj2020** [comment]
HI Team,

As per above comment i have done the changes of Base branch. Please review the changes.

**Comment by yecli** [comment]
Now PR has 2465 changed files.
If you want to make PR to platform 2.x - you need to use support/2.x-dev branch as a target branch and the same branch in your fork as a source branch.
Now the source branch is master, which causes the problem. Reapply your changes in your support/2.x-dev branch and create a PR from it.

**Comment by anuj2020** [comment]
HI Team,

I have done the changes as per your comments. Now the new PR is "Updated method to read the Web and Core xml file #2017"

**Comment by yecli** [comment]
Closing as duplicate

**Pull request closed without merging**
