### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and reduce memory allocations as opposed to the existing locking mechanism.

### CODE REVIEW

**Comment by OlegoO** [comment]
Hi @MarkCiliaVincenti
Do you have any metrics, or result that your code improves performance and reduce memory?
Do you already use Virto Commerce?

**Comment by MarkCiliaVincenti** [comment]
> Hi @MarkCiliaVincenti Do you have any metrics, or result that your code improves performance and reduce memory? Do you already use Virto Commerce?

Please open https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/4096117409/jobs/7063532645 and look at the results of the benchmark, ignoring the ones for NumberOfLocks=10000, Contention=10000

Compare AsyncKeyedLock to AsyncDuplicateLockFromAutoCrud (which is basically the same code you're using). You will see that your current code has up to 96% MORE allocations compared to AsyncKeyedLock. As for the performance, it varies, but they are close. The main benefit you'll get is reduced allocations.

**Comment by MarkCiliaVincenti** [comment]
@OlegoO do you need anything else?

**Comment by MarkCiliaVincenti** [comment]
💪🏼

**Comment by MarkCiliaVincenti** [comment]
@OlegoO ?

**Comment by MarkCiliaVincenti** [comment]
@OlegoO

**Comment by MarkCiliaVincenti** [comment]
@OlegoO do you need anything else?

**Comment by MarkCiliaVincenti** [comment]
@OlegoO ?

**Comment by MarkCiliaVincenti** [comment]
@OlegoO  are you interested or shall I close this PR?

**Pull request closed without merging**
