### PR TITLE
Platform notifications: Allow to use objects with any types in Liquid templates is not just an derived from IEntity #1116

### PR DESCRIPTION
**Pull request by megafreeman**

### CODE REVIEW

**Comment by asvishnyakov** [comment]
I believe you should leave only one RegisterTypeAsDrop and inherit IEntity from ILiquidizable

**Comment by megafreeman** [comment]
Some edits and improvements were made in accordance with the comments @asvishnyakov @alex765022 @tatarincev

**Comment by tatarincev** [comment]
`IValueObject` marker interface should be inherited only by ValueObject type. And the code that is responsible for the making of ILiquidizable must be supplemented with new `IValueObject` interface check.

**Comment by megafreeman** [comment]
Moved to https://github.com/VirtoCommerce/vc-platform/pull/1127

**Pull request closed without merging**
